node.name: logstash-flask
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50
queue.type: memory
queue.max_bytes: 1gb
api.enabled: true
api.http.host: "0.0.0.0"
api.http.port: 9600
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
log.level: info